#+feature dynamic-literals
package compiler

// Token kinds, ported from src/parser.y's %token declarations and src/keywords.gperf's
// keyword table (originally generated by gperf into a perfect-hash lookup; here it's just
// a plain map -- at ~30 entries there's no measurable benefit to a generated hash function,
// so a map is the simpler, equally-fast choice).

import "../values"

Token_Kind :: enum {
	EOF,
	Int, Float, String, Object, Error, Id,

	// Keywords
	If, Else, Elseif, Endif,
	For, In, Endfor,
	Fork, Endfork,
	Return,
	While, Endwhile,
	Try, Except, Finally, Endtry, Any,
	Break, Continue,

	// Multi-char operators
	Eq, Ne, Le, Ge, And, Or, Arrow, To,

	// Single-char operators/punctuation
	Assign, Question, Pipe, Lt, Gt,
	Plus, Minus, Star, Slash, Percent, Caret, Bang,
	Dot, Colon, LBracket, RBracket, LBrace, RBrace, LParen, RParen,
	Comma, Semi, Dollar, At, Backtick, Quote,
}

Token :: struct {
	kind:      Token_Kind,
	line:      int,
	int_val:   i32,
	float_val: f64,
	str_val:   string, // owned for .String/.Id, borrowed (static) otherwise
	obj_val:   values.Objid,
	err_val:   values.Error,
}

// Keyword -> (token kind, minimum DB_Version, error value if kind == .Error). Ported
// verbatim from keywords.gperf; a keyword whose version exceeds the program's DB version is
// lexed as a plain identifier instead (see lexer.odin), matching the original's "renaming
// old use of new keyword" behavior for programs written before that keyword existed.
Keyword_Info :: struct {
	kind:    Token_Kind,
	version: int,
	err:     values.Error,
}

keywords := map[string]Keyword_Info {
	"if"       = {.If, DBV_Prehistory, .E_NONE},
	"else"     = {.Else, DBV_Prehistory, .E_NONE},
	"elseif"   = {.Elseif, DBV_Prehistory, .E_NONE},
	"endif"    = {.Endif, DBV_Prehistory, .E_NONE},
	"for"      = {.For, DBV_Prehistory, .E_NONE},
	"in"       = {.In, DBV_Prehistory, .E_NONE},
	"endfor"   = {.Endfor, DBV_Prehistory, .E_NONE},
	"fork"     = {.Fork, DBV_Prehistory, .E_NONE},
	"endfork"  = {.Endfork, DBV_Prehistory, .E_NONE},
	"return"   = {.Return, DBV_Prehistory, .E_NONE},
	"while"    = {.While, DBV_Prehistory, .E_NONE},
	"endwhile" = {.Endwhile, DBV_Prehistory, .E_NONE},
	"try"      = {.Try, DBV_Exceptions, .E_NONE},
	"except"   = {.Except, DBV_Exceptions, .E_NONE},
	"finally"  = {.Finally, DBV_Exceptions, .E_NONE},
	"endtry"   = {.Endtry, DBV_Exceptions, .E_NONE},
	"ANY"      = {.Any, DBV_Exceptions, .E_NONE},
	"break"    = {.Break, DBV_BreakCont, .E_NONE},
	"continue" = {.Continue, DBV_BreakCont, .E_NONE},
	"E_NONE"    = {.Error, DBV_Prehistory, .E_NONE},
	"E_TYPE"    = {.Error, DBV_Prehistory, .E_TYPE},
	"E_DIV"     = {.Error, DBV_Prehistory, .E_DIV},
	"E_PERM"    = {.Error, DBV_Prehistory, .E_PERM},
	"E_PROPNF"  = {.Error, DBV_Prehistory, .E_PROPNF},
	"E_VERBNF"  = {.Error, DBV_Prehistory, .E_VERBNF},
	"E_VARNF"   = {.Error, DBV_Prehistory, .E_VARNF},
	"E_INVIND"  = {.Error, DBV_Prehistory, .E_INVIND},
	"E_RECMOVE" = {.Error, DBV_Prehistory, .E_RECMOVE},
	"E_MAXREC"  = {.Error, DBV_Prehistory, .E_MAXREC},
	"E_RANGE"   = {.Error, DBV_Prehistory, .E_RANGE},
	"E_ARGS"    = {.Error, DBV_Prehistory, .E_ARGS},
	"E_NACC"    = {.Error, DBV_Prehistory, .E_NACC},
	"E_INVARG"  = {.Error, DBV_Prehistory, .E_INVARG},
	"E_QUOTA"   = {.Error, DBV_Prehistory, .E_QUOTA},
	"E_FLOAT"   = {.Error, DBV_Float, .E_FLOAT},
}

// DB_Version thresholds, duplicated from dbfile's (to avoid a compiler->dbfile package
// dependency for four constants -- these are language/grammar facts, not file-format facts).
DBV_Prehistory :: 0
DBV_Exceptions :: 1
DBV_BreakCont :: 2
DBV_Float :: 3
